name: Desafio 1 do curso de Github Actions da LinuxTips

on:
  workflow_dispatch:

jobs:
   desafio_1:
      runs-on: ubuntu-latest
      steps:
        - name: Baixa a imagem docker do Alpine
          run: docker pull alpine@3.19.8
        
        - name: Lista as imagens Docker que foram baixadas
          run: docker image ls

        - name: Faz um scan de vulnerabilidades com docker scout
          uses: docker/scout-action@v1
          with:
            command: cves
            image: alpine@3.19.8
            sarif-file: sarif.output.json
            summary: true