name: Vendo arquivos compartilhados entre jobs

on:
  push:
    branches:
    - main

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versao do Ubuntu
        run: cat /etc/os-release

      - name: Exibir uma mensagem
        run: echo "Estou fazendo o curso de Github Actions da LinuxTips" > ${{ github.workspace }}/mensagem.txt

      - uses: actions/upload-artifact@v4
        with:
         name: strigus-upload
         path: ${{ github.workspace }}/mensagem.txt

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: Ver conteudo do diretorio
        run: ls -lha

      - uses: actions/download-artifact@v5
        with:
          name: strigus-upload
          path: strigus

      - name: Ver conteudo do diretorio
        run: ls -lha && ls ./strigus/

      - name: Move arquivo mensagem.txt 
        run: mv strigus/mensagem.txt . && rm -rf ./strigus/
      
      - name: Ver conteudo do diretorio
        run: ls -lha

      - name: Acessa arquivo mensagem
        run: cat mensagem.txt
